import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header.js/Header";
import Navbar from "../components/Nav.js/Navbar";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Hulo clone </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
			
        {/* header */}
        <Header />
        {/* nav */}

        <Navbar />
        

			</main>
		</div>
	);
}
